### ISSUE TITLE
Not all workers get shutdown message

### ISSUE THREAD

**Issue by ryandesign** [andrewrk/naught#63]
Having just found naught, I'm trying to integrate it into my project, and am having trouble. To rule out my project's code, I created a new basic web server, and I'm having trouble with that too. Here's the simple server.js:

```
var cluster = require('cluster');
var http = require('http');

var server = http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Worker ' + cluster.worker.id + ' says hello');
});

server.listen(3000, function () {
  if (process.send) {
    console.log('Worker %s started', cluster.worker.id);
    process.send('online');
  }
});

process.on('message', function (message) {
  console.log('Worker %s got message %s', cluster.worker.id, message);
  if (message === 'shutdown') {
    server.close();
  }
});
```

I installed naught 1.4.1. In one terminal window, I use naught to start 3 copies of my server, and then in another window I use naught to stop it. After this, the first window has the following content:

```
$ ./node_modules/.bin/naught start --worker-count 3 --daemon-mode false --stderr - --stdout - server.js
Worker 1 started
Worker 3 started
Worker 2 started
Worker 3 got message shutdown
$
```

The other window has the following content:

```
$ ./node_modules/.bin/naught stop
ShutdownOld. booting: 0, online: 2, dying: 1, new_online: 0
ShutdownOld. booting: 0, online: 1, dying: 2, new_online: 0
ShutdownOld. booting: 0, online: 0, dying: 3, new_online: 0
OldExit. booting: 0, online: 0, dying: 2, new_online: 0
OldExit. booting: 0, online: 0, dying: 1, new_online: 0
OldExit. booting: 0, online: 0, dying: 0, new_online: 0
$
```

Why didn't workers 1 and 2 get a shutdown message? And having not received a shutdown message, why did they shut down?

Sometimes two of the three servers get a shutdown messages. Sometimes just one of them does.

This is with the following version of node and OS X:

```
$ node -v
v0.11.14
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10
BuildVersion:   14A388b
$
```

**Comment by drywheat** [comment]
Node v0.12.x has been out for over 2 months now. :-)
