### ISSUE TITLE
A script to either naught start or naught deploy if naught is already running

### ISSUE THREAD

**Issue by gavacho** [andrewrk/naught#72]
I'd like to create a script which either starts naught (when it's not running) or does `naught deploy`.  Can anyone provide such an example?  Should I branch on the existence of the pidfile?

**Comment by gavacho** [comment]
I've attempted to examine the standard output of the `naught status` command for the existence of the "server not running" string.  However, the std out is empty :(

**Comment by mathrawka** [comment]
I use upstart to start the process using naught at system bootup. After
that, it should always be running.

So in the deploy process I make a call to 'naught deploy'

**Comment by gavacho** [comment]
Ah, that makes a lot of sense.  Thanks

**Comment by rbhalla** [comment]
@mathrawka I am having troubles writing my own upstart script, it seems to be latching onto the wrong PID. How did you solve this?
