### ISSUE TITLE
Naught deploy blocks until old process exits

### ISSUE THREAD

**Issue by sonnysideup** [andrewrk/naught#79]
`naught deploy` blocks until the old version of the application exits. I can certainly understand why some people would want this behavior, but I believe another valid use-case is where we "fire and forget."  This is typical during a rolling deploy.

What are you thoughts?

**Comment by andrewrk** [comment]
Why do you have to wait for naught deploy to finish?

**Comment by drywheat** [comment]
There may be a unit of work that needs a little time to finish before the original process exists. This is not an uncommon deployment scenario.

**Comment by andrewrk** [comment]
Can you help me understand? It sounds like you're asking for it to simultaneously block and not block.

**Comment by drywheat** [comment]
I'm asking for the `deploy` command to not block, but still allow the old process to block until it finishes. This would let you easily automate a deploy for a process that handles long-lived requests.

1. You invoke `naught deploy`, it rolls a new process and exits cleanly
2. The old process blocks the new one from receiving requests until it finishes and exits.
